version: '2'
services:
  yggtorrentprez:
    build : ./
    image : 'yggtorrentprez'
    stdin_open: true
    tty: true
    volumes :
      - ./scripts:/tmp/scripts
      - ./input:/tmp/input
      - ./output:/tmp/output
      - ./torrent:/tmp/torrent
